_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 71
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.9
            "6": 4.46.2
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": darwin-arm64
